// mf-detail/src/components/Card.svelte
<script>
  import { API_URL } from "../config";

  export let data;
</script>

<style>
  .card {
    width: 30rem;
  }

  img {
    align-self: center;
    padding: 1rem;
    height: 20rem;
  }
</style>

<div class="card">
  <img src={`${API_URL}/${data.logo_url}`} class="card-img-top" alt="logo" />
  <div class="card-body">
    <h4 class="card-title">{data.name}</h4>
    <p class="card-text">{data.description}</p>
    <a href={data.homepage_url} target="_blank" class="btn btn-primary">
      Homepage
    </a>
  </div>
</div>

// mf-browse/src/components/Card.jsx
import { API_URL } from "../config";
import "./Card.css";

export default function Card({ data }) {
  return (
    <div className="col-6 col-md-4 col-lg-3 p-2">
      <a
        className="card text-center card-custom"
        href={`/items/${data.id}`}
        data-link
      >
        <div className="card-body">
          <h4 className="card-title">{data.name}</h4>
          <img
            src={`${API_URL}/${data.logo_url}`}
            width="100"
            height="100"
            alt="logo"
          />
        </div>
      </a>
    </div>
  );
}
