// mf-browse/src/components/ErrorMessage.jsx
import "./ErrorMessage.css";

export default function Error({ title = "Error", text }) {
  return (
    <section className="d-flex align-items-center justify-content-center p-4 error-message">
      <div className="card text-center text-danger">
        <div className="card-body">
          <h5 className="card-title">{title}</h5>
          {!!text && <p className="card-text">{text}</p>}
        </div>
      </div>
    </section>
  );
}

// micro-frontends/tech-card/src/components/ErrorMessage.svelte
<script>
  export let title = "Error";
  export let text;
</script>

<style>
  .card {
    width: 30rem;
  }

  .card-title {
    font-size: 8rem;
    font-weight: 200;
  }

  p {
    font-size: 2rem;
    font-weight: 200;
  }
</style>

<div class="card text-center text-danger">
  <div class="card-body">
    <h5 class="card-title">{title}</h5>
    {#if text}
      <p class="card-text">{text}</p>
    {/if}
  </div>
</div>
